[package]
name = "test_lib"
version = "0.1.0"
edition = "2021"
crate_type = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
